//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace FontDemo
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int icon = 0x7f020000;
        }
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Id
        {
            
            public const int fontView = 0x7f040036;
        }
        
        public sealed class String
        {
            
            public const int FontFailTitle = 0x7f050000;
            
            public const int FontFailText = 0x7f050001;
        }
    }
}
