//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Support4Demos
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int alert_dialog_icon = 0x7f020000;
            
            public const int app_sample_code = 0x7f020001;
            
            public const int red = 0x7f020002;
            
            public const int blue = 0x7f020003;
            
            public const int green = 0x7f020004;
            
            public const int yellow = 0x7f020005;
        }
        
        public sealed class Layouts
        {
            
            public const int accessibility_delegate = 0x7f030000;
            
            public const int accessibility_manager = 0x7f030001;
            
            public const int fragment_arguments_support = 0x7f030002;
            
            public const int fragment_context_menu = 0x7f030003;
            
            public const int fragment_dialog = 0x7f030004;
            
            public const int fragment_dialog_or_activity = 0x7f030005;
            
            public const int fragment_hide_show_support = 0x7f030006;
            
            public const int fragment_layout_support = 0x7f030007;
            
            public const int fragment_menu = 0x7f030008;
            
            public const int fragment_pager = 0x7f030009;
            
            public const int fragment_pager_list = 0x7f03000a;
            
            public const int fragment_retain_instance = 0x7f03000b;
            
            public const int fragment_stack = 0x7f03000c;
            
            public const int fragment_tabs = 0x7f03000d;
            
            public const int fragment_tabs_pager = 0x7f03000e;
            
            public const int hello_world = 0x7f03000f;
            
            public const int labeled_text_edit = 0x7f030010;
            
            public const int list_item_icon_text = 0x7f030011;
            
            public const int local_service_broadcaster = 0x7f030012;
            
            public const int receive_result = 0x7f030013;
            
            public const int send_result = 0x7f030014;
            
            public const int sharing_receiver_support = 0x7f030015;
            
            public const int sharing_support = 0x7f030016;
            
            public const int simple_list_item_checkable_1 = 0x7f030017;
        }
        
        public sealed class Anims
        {
            
            public const int decelerate_quint = 0x7f040000;
            
            public const int fragment_slide_left_enter = 0x7f040001;
            
            public const int fragment_slide_left_exit = 0x7f040002;
            
            public const int fragment_slide_right_enter = 0x7f040003;
            
            public const int fragment_slide_right_exit = 0x7f040004;
        }
        
        public sealed class Ids
        {
            
            public const int accessibility_state = 0x7f050035;
            
            public const int text = 0x7f050036;
            
            public const int embedded = 0x7f050037;
            
            public const int created = 0x7f050038;
            
            public const int embedded_land = 0x7f050039;
            
            public const int long_press = 0x7f05003a;
            
            public const int show = 0x7f05003b;
            
            public const int show_dialog = 0x7f05003c;
            
            public const int inline_text = 0x7f05003d;
            
            public const int frag1hide = 0x7f05003e;
            
            public const int fragment1 = 0x7f05003f;
            
            public const int frag2hide = 0x7f050040;
            
            public const int fragment2 = 0x7f050041;
            
            public const int titles = 0x7f050042;
            
            public const int details = 0x7f050043;
            
            public const int menu1 = 0x7f050044;
            
            public const int menu2 = 0x7f050045;
            
            public const int pager = 0x7f050046;
            
            public const int goto_first = 0x7f050047;
            
            public const int goto_last = 0x7f050048;
            
            public const int progress_horizontal = 0x7f050049;
            
            public const int restart = 0x7f05004a;
            
            public const int simple_fragment = 0x7f05004b;
            
            public const int home = 0x7f05004c;
            
            public const int new_fragment = 0x7f05004d;
            
            public const int delete_fragment = 0x7f05004e;
            
            public const int realtabcontent = 0x7f05004f;
            
            public const int msg = 0x7f050050;
            
            public const int saved = 0x7f050051;
            
            public const int icon = 0x7f050052;
            
            public const int start = 0x7f050053;
            
            public const int stop = 0x7f050054;
            
            public const int callback = 0x7f050055;
            
            public const int results = 0x7f050056;
            
            public const int get = 0x7f050057;
            
            public const int corky = 0x7f050058;
            
            public const int violet = 0x7f050059;
            
            public const int app_info = 0x7f05005a;
            
            public const int share_text = 0x7f05005b;
            
            public const int share_file = 0x7f05005c;
            
            public const int share_multiple_file = 0x7f05005d;
            
            public const int invisible_item = 0x7f05005e;
            
            public const int a_item = 0x7f05005f;
            
            public const int b_item = 0x7f050060;
            
            public const int c_item = 0x7f050061;
            
            public const int d_item = 0x7f050062;
            
            public const int e_item = 0x7f050063;
            
            public const int f_item = 0x7f050064;
            
            public const int g_item = 0x7f050065;
            
            public const int h_item = 0x7f050066;
            
            public const int excl_item = 0x7f050067;
        }
        
        public sealed class Strings
        {
            
            public const int activity_sample_code = 0x7f060000;
            
            public const int hello_world = 0x7f060001;
            
            public const int alert_dialog_two_buttons_title = 0x7f060002;
            
            public const int alert_dialog_ok = 0x7f060003;
            
            public const int alert_dialog_cancel = 0x7f060004;
            
            public const int initial_text = 0x7f060005;
            
            public const int pick_result = 0x7f060006;
            
            public const int corky = 0x7f060007;
            
            public const int violet = 0x7f060008;
            
            public const int receive_result_instructions = 0x7f060009;
            
            public const int receive_result_result = 0x7f06000a;
            
            public const int fragment_alert_dialog_support = 0x7f06000b;
            
            public const int fragment_arguments_support = 0x7f06000c;
            
            public const int fragment_arguments_msg = 0x7f06000d;
            
            public const int fragment_arguments_embedded = 0x7f06000e;
            
            public const int fragment_arguments_embedded_land = 0x7f06000f;
            
            public const int fragment_custom_animation_support = 0x7f060010;
            
            public const int fragment_hide_show_support = 0x7f060011;
            
            public const int fragment_context_menu_support = 0x7f060012;
            
            public const int fragment_context_menu_msg = 0x7f060013;
            
            public const int long_press = 0x7f060014;
            
            public const int fragment_dialog_support = 0x7f060015;
            
            public const int show = 0x7f060016;
            
            public const int fragment_dialog_or_activity_support = 0x7f060017;
            
            public const int fragment_dialog_or_activity_msg = 0x7f060018;
            
            public const int fragment_dialog_or_activity_inline = 0x7f060019;
            
            public const int fragment_layout_support = 0x7f06001a;
            
            public const int fragment_list_array_support = 0x7f06001b;
            
            public const int fragment_menu_support = 0x7f06001c;
            
            public const int fragment_menu_msg = 0x7f06001d;
            
            public const int fragment1menu = 0x7f06001e;
            
            public const int fragment2menu = 0x7f06001f;
            
            public const int fragment_nesting_tabs_support = 0x7f060020;
            
            public const int fragment_retain_instance_support = 0x7f060021;
            
            public const int fragment_retain_instance_msg = 0x7f060022;
            
            public const int restart = 0x7f060023;
            
            public const int fragment_receive_result_support = 0x7f060024;
            
            public const int fragment_stack_support = 0x7f060025;
            
            public const int home = 0x7f060026;
            
            public const int new_fragment = 0x7f060027;
            
            public const int delete_fragment = 0x7f060028;
            
            public const int fragment_tabs = 0x7f060029;
            
            public const int fragment_tabs_pager = 0x7f06002a;
            
            public const int fragment_pager_support = 0x7f06002b;
            
            public const int first = 0x7f06002c;
            
            public const int last = 0x7f06002d;
            
            public const int fragment_state_pager_support = 0x7f06002e;
            
            public const int loader_cursor_support = 0x7f06002f;
            
            public const int loader_retained_support = 0x7f060030;
            
            public const int loader_custom_support = 0x7f060031;
            
            public const int loader_throttle_support = 0x7f060032;
            
            public const int local_service_broadcaster = 0x7f060033;
            
            public const int local_service_broadcaster_msg = 0x7f060034;
            
            public const int start_service = 0x7f060035;
            
            public const int stop_service = 0x7f060036;
            
            public const int accessibility_manager_title = 0x7f060037;
            
            public const int accessibility_manager_instructions = 0x7f060038;
            
            public const int accessibility_manager_no_enabled_services = 0x7f060039;
            
            public const int accessibility_manager_enabled_service = 0x7f06003a;
            
            public const int accessibility_manager_accessibility_state = 0x7f06003b;
            
            public const int accessibility_delegate_title = 0x7f06003c;
            
            public const int accessibility_delegate_instructions = 0x7f06003d;
            
            public const int accessibility_delegate_button = 0x7f06003e;
            
            public const int accessibility_delegate_custom_text_added = 0x7f06003f;
            
            public const int share_text = 0x7f060040;
            
            public const int share_file = 0x7f060041;
            
            public const int share_multiple_file = 0x7f060042;
            
            public const int sharing_support_title = 0x7f060043;
            
            public const int sharing_receiver_title = 0x7f060044;
        }
        
        public sealed class Styles
        {
            
            public const int ThemeHolo = 0x7f070000;
            
            public const int ThemeDialogWhenLarge = 0x7f070001;
        }
        
        public sealed class Menus
        {
            
            public const int shortcuts = 0x7f080000;
        }
        
        public sealed class Styleables
        {
            
            public sealed class FragmentArguments
            {
                
                public const int label = Android.R.Attr.Label;
                
public static readonly int[] AllIds = new[] { Android.R.Attr.Label };
            }
        }
    }
}
