//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace dot42AppNUnit
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Ids
        {
            
            public const int MyText = 0x7f030035;
            
            public const int MyImage = 0x7f030036;
        }
    }
}
