//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace MapsTest
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Id
        {
            
            public const int theMap = 0x7f030038;
        }
    }
}
