//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SorterenMaar
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int BorderBackground = 0x7f020000;
            
            public const int ear = 0x7f020001;
            
            public const int Emma = 0x7f020002;
            
            public const int Inge = 0x7f020003;
            
            public const int Laura = 0x7f020004;
            
            public const int Laura_drawing = 0x7f020005;
            
            public const int Thor = 0x7f020006;
        }
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f030000;
            
            public const int SortTaskLayout = 0x7f030001;
        }
        
        public sealed class Raw
        {
            
            public const int SortGame = 0x7f040000;
        }
        
        public sealed class Id
        {
            
            public const int GameFrame = 0x7f050038;
            
            public const int Scoreboard = 0x7f050039;
            
            public const int TaskText = 0x7f05003a;
            
            public const int earImage = 0x7f05003b;
            
            public const int Task = 0x7f05003c;
            
            public const int DropZones = 0x7f05003d;
            
            public const int submenu = 0x7f05003e;
        }
        
        public sealed class Color
        {
            
            public const int accent_blue = 0x7f060000;
            
            public const int light_blue = 0x7f060001;
        }
        
        public sealed class Style
        {
            
            public const int MyActionBar = 0x7f070000;
            
            public const int MyTheme = 0x7f070001;
            
            public const int MyTextView = 0x7f070002;
            
            public const int MyTextViewColored = 0x7f070003;
        }
        
        public sealed class Menu
        {
            
            public const int OptionsMenu = 0x7f080000;
        }
    }
}
