//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace LunarLander
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int app_lunar_lander = 0x7f020000;
            
            public const int earthrise = 0x7f020001;
            
            public const int lander_crashed = 0x7f020002;
            
            public const int lander_firing = 0x7f020003;
            
            public const int lander_plain = 0x7f020004;
        }
        
        public sealed class Layouts
        {
            
            public const int lunar_layout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int lunar = 0x7f040035;
            
            public const int text = 0x7f040036;
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f050000;
            
            public const int menu_start = 0x7f050001;
            
            public const int menu_stop = 0x7f050002;
            
            public const int menu_pause = 0x7f050003;
            
            public const int menu_resume = 0x7f050004;
            
            public const int menu_easy = 0x7f050005;
            
            public const int menu_medium = 0x7f050006;
            
            public const int menu_hard = 0x7f050007;
            
            public const int mode_ready = 0x7f050008;
            
            public const int mode_pause = 0x7f050009;
            
            public const int mode_lose = 0x7f05000a;
            
            public const int mode_win_prefix = 0x7f05000b;
            
            public const int mode_win_suffix = 0x7f05000c;
            
            public const int message_stopped = 0x7f05000d;
            
            public const int message_off_pad = 0x7f05000e;
            
            public const int message_too_fast = 0x7f05000f;
            
            public const int message_bad_angle = 0x7f050010;
            
            public const int lunar_layout_text_text = 0x7f050011;
        }
    }
}
