//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SimpleAnimation
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Id
        {
        }
    }
}
