//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Dot42.Tests.Compiler
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Id
        {
        }
    }
}
