//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace ImportJar
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layout
        {
            
            public const int GsonActivity = 0x7f020000;
        }
        
        public sealed class Id
        {
            
            public const int mainLayout = 0x7f030036;
            
            public const int label = 0x7f030037;
            
            public const int editor = 0x7f030038;
            
            public const int button = 0x7f030039;
        }
    }
}
