//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace UsingSuportLibrary
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layout
        {
            
            public const int FragmentDialogActivity_Layout = 0x7f020000;
        }
        
        public sealed class Id
        {
        }
    }
}
