//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support4Demos
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Ids
        {
        }
    }
}
