//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace UsingButton
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Background = 0x7f020000;
            
            public const int Icon = 0x7f020001;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int myButton = 0x7f040035;
        }
    }
}
