// This file was auto-generated by 'NAnt.BuildTools.Tasks' version '1.0.0.0' from 'ProductVersion.xml'
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("2.0.1.87")]
[assembly: AssemblyConfiguration("")]
