//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SimpleMenu
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int tbLog = 0x7f040035;
            
            public const int item1 = 0x7f040036;
            
            public const int firstGroup = 0x7f040037;
            
            public const int groupItem1 = 0x7f040038;
            
            public const int submenu = 0x7f040039;
            
            public const int submenu_item1 = 0x7f04003a;
        }
        
        public sealed class Menus
        {
            
            public const int Menu = 0x7f050000;
        }
    }
}
