//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Dot42.TodoApi.Version_1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Dot42:TodoApi:1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Version", Namespace="urn:Dot42:TodoApi:1.0", IsNullable=false)]
    public enum VersionType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        v1_0,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Dot42:TodoApi:1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Todos", Namespace="urn:Dot42:TodoApi:1.0", IsNullable=false)]
    public partial class TodosType {
        
        private TodoType[] todoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Todo")]
        public TodoType[] Todo {
            get {
                return this.todoField;
            }
            set {
                this.todoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Dot42:TodoApi:1.0")]
    public partial class TodoType {
        
        private bool isDoneField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.DateTime expirationDateField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        public bool IsDone {
            get {
                return this.isDoneField;
            }
            set {
                this.isDoneField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Dot42:TodoApi:1.0")]
    [System.Xml.Serialization.XmlRootAttribute("TodoIds", Namespace="urn:Dot42:TodoApi:1.0", IsNullable=false)]
    public partial class TodoIdsType {
        
        private string[] todoIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TodoId")]
        public string[] TodoId {
            get {
                return this.todoIdField;
            }
            set {
                this.todoIdField = value;
            }
        }
    }
}
