//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace BluetoothChat
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int app_icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int custom_title = 0x7f030000;
            
            public const int device_list = 0x7f030001;
            
            public const int device_name = 0x7f030002;
            
            public const int main = 0x7f030003;
            
            public const int message = 0x7f030004;
        }
        
        public sealed class Ids
        {
            
            public const int title_left_text = 0x7f040035;
            
            public const int title_right_text = 0x7f040036;
            
            public const int title_paired_devices = 0x7f040037;
            
            public const int paired_devices = 0x7f040038;
            
            public const int title_new_devices = 0x7f040039;
            
            public const int new_devices = 0x7f04003a;
            
            public const int button_scan = 0x7f04003b;
            
            public const int @in = 0x7f04003c;
            
            public const int edit_text_out = 0x7f04003d;
            
            public const int button_send = 0x7f04003e;
            
            public const int secure_connect_scan = 0x7f04003f;
            
            public const int insecure_connect_scan = 0x7f040040;
            
            public const int discoverable = 0x7f040041;
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f050000;
            
            public const int send = 0x7f050001;
            
            public const int not_connected = 0x7f050002;
            
            public const int bt_not_enabled_leaving = 0x7f050003;
            
            public const int title_connecting = 0x7f050004;
            
            public const int title_connected_to = 0x7f050005;
            
            public const int title_not_connected = 0x7f050006;
            
            public const int scanning = 0x7f050007;
            
            public const int select_device = 0x7f050008;
            
            public const int none_paired = 0x7f050009;
            
            public const int none_found = 0x7f05000a;
            
            public const int title_paired_devices = 0x7f05000b;
            
            public const int title_other_devices = 0x7f05000c;
            
            public const int button_scan = 0x7f05000d;
            
            public const int secure_connect = 0x7f05000e;
            
            public const int insecure_connect = 0x7f05000f;
            
            public const int discoverable = 0x7f050010;
        }
        
        public sealed class Menus
        {
            
            public const int option_menu = 0x7f060000;
        }
    }
}
