'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace StartSecondActivity
    
    Public NotInheritable Class R
        
        Public NotInheritable Class Drawables
            
            Public Const Icon As Integer = 2130837504
        End Class
        
        Public NotInheritable Class Layouts
            
            Public Const MainLayout As Integer = 2130903040
            
            Public Const SecondActivity As Integer = 2130903041
        End Class
    End Class
End Namespace
