//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SimpleFragment
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int LeftFragment = 0x7f030000;
            
            public const int MainLayout = 0x7f030001;
            
            public const int RightFragment = 0x7f030002;
        }
        
        public sealed class Ids
        {
            
            public const int myLeftFragment = 0x7f040035;
            
            public const int myRightFragment = 0x7f040036;
        }
    }
}
