//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Dot42Application1
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int AppWidget = 0x7f020000;
        }
        
        public sealed class Layout
        {
            
            public const int Activity1_Layout = 0x7f030000;
            
            public const int AppWidget1_Layout = 0x7f030001;
            
            public const int MainActivityLayout = 0x7f030002;
        }
        
        public sealed class Xml
        {
            
            public const int dot42_app_widget_provider_0 = 0x7f040000;
        }
        
        public sealed class Id
        {
            
            public const int label = 0x7f050038;
            
            public const int editor = 0x7f050039;
            
            public const int button = 0x7f05003a;
            
            public const int item1 = 0x7f05003b;
            
            public const int firstGroup = 0x7f05003c;
            
            public const int groupItem1 = 0x7f05003d;
            
            public const int submenu = 0x7f05003e;
            
            public const int submenu_item1 = 0x7f05003f;
        }
        
        public sealed class Plurals
        {
            
            public const int numerOfBirdsInTheSky = 0x7f060000;
        }
        
        public sealed class String
        {
            
            public const int some_string = 0x7f070000;
            
            public const int second_string = 0x7f070001;
            
            public const int testString = 0x7f070002;
            
            public const int testString2 = 0x7f070003;
            
            public const int Hello_world = 0x7f070004;
        }
        
        public sealed class Menu
        {
            
            public const int Menu1 = 0x7f080000;
        }
    }
}
