//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace AppWidget1
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f020000;
            
            public const int WidgetLayout = 0x7f020001;
        }
        
        public sealed class Xml
        {
            
            public const int dot42_app_widget_provider_0 = 0x7f030000;
        }
        
        public sealed class Id
        {
        }
    }
}
