//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace dot42Application6
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Id
        {
        }
        
        public sealed class Color
        {
            
            public const int pressed_theme_example = 0x7f040000;
        }
    }
}
