//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Case668
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Ids
        {
        }
        
        public sealed class Styleables
        {
            
            public sealed class FragmentArguments
            {
                
                public const int label = Android.R.Attr.Label;
                
public static readonly int[] AllIds = new[] { Android.R.Attr.Label };
            }
        }
    }
}
