//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace WcfClient
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int Version = 0x7f040035;
            
            public const int AddButton = 0x7f040036;
            
            public const int TodoList = 0x7f040037;
        }
    }
}
