//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace DllImportTest
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainActivityLayout = 0x7f020000;
        }
        
        public sealed class Ids
        {
            
            public const int label = 0x7f030035;
        }
    }
}
