//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int ic_launcher = 0x7f020000;
        }
        
        public sealed class Layout
        {
            
            public const int activity_to_do = 0x7f030000;
            
            public const int row_list_to_do = 0x7f030001;
        }
        
        public sealed class Id
        {
            
            public const int LinearLayout1 = 0x7f040036;
            
            public const int textViewTitle = 0x7f040037;
            
            public const int loadingProgressBar = 0x7f040038;
            
            public const int textNewToDo = 0x7f040039;
            
            public const int buttonAddToDo = 0x7f04003a;
            
            public const int listViewToDo = 0x7f04003b;
            
            public const int checkToDoItem = 0x7f04003c;
            
            public const int menu_refresh = 0x7f04003d;
        }
        
        public sealed class String
        {
            
            public const int app_name = 0x7f050000;
            
            public const int add_textbox_hint = 0x7f050001;
            
            public const int add_button_text = 0x7f050002;
            
            public const int mobile_services = 0x7f050003;
            
            public const int menu_refresh = 0x7f050004;
            
            public const int checkbox_text = 0x7f050005;
        }
        
        public sealed class Style
        {
            
            public const int AppBaseTheme = 0x7f060000;
            
            public const int AppTheme = 0x7f060001;
        }
        
        public sealed class Menu
        {
            
            public const int activity_main = 0x7f070000;
        }
    }
}
