//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int ic_launcher = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int activity_to_do = 0x7f030000;
            
            public const int row_list_to_do = 0x7f030001;
        }
        
        public sealed class Ids
        {
            
            public const int LinearLayout1 = 0x7f04000e;
            
            public const int textViewTitle = 0x7f04000f;
            
            public const int loadingProgressBar = 0x7f040010;
            
            public const int textNewToDo = 0x7f040011;
            
            public const int buttonAddToDo = 0x7f040012;
            
            public const int listViewToDo = 0x7f040013;
            
            public const int checkToDoItem = 0x7f040014;
            
            public const int menu_refresh = 0x7f040015;
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f050000;
            
            public const int add_textbox_hint = 0x7f050001;
            
            public const int add_button_text = 0x7f050002;
            
            public const int mobile_services = 0x7f050003;
            
            public const int menu_refresh = 0x7f050004;
            
            public const int checkbox_text = 0x7f050005;
        }
        
        public sealed class Styles
        {
            
            public const int AppBaseTheme = 0x7f060000;
            
            public const int AppTheme = 0x7f060001;
        }
        
        public sealed class Menus
        {
            
            public const int activity_main = 0x7f070000;
        }
    }
}
