using System.Collections.Generic;

namespace Dot42.DexLib.Instructions
{
    public partial class OpCodeInfo
    {
        /// <summary>
        /// Class ctor
        /// </summary>
        static OpCodeInfo()
        {
            map = new Dictionary<OpCodes, OpCodeInfo>();
            foreach (var entry in list)
            {
                map[entry.Code] = entry;
            }
        }

        /// <summary>
        /// Gets infy by code.
        /// </summary>
        public static OpCodeInfo Get(OpCodes code)
        {
            return map[code];
        }

        private static readonly Dictionary<OpCodes, OpCodeInfo> map;
        private static readonly OpCodeInfo[] list = new[] {
            new OpCodeInfo(OpCodes.Nop), 
            new OpCodeInfo(OpCodes.Move, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Move_from16, RegisterFlags.Destination8Bits, RegisterFlags.Source16Bits), 
            new OpCodeInfo(OpCodes.Move_16, RegisterFlags.Destination16Bits, RegisterFlags.Source16Bits), 
            new OpCodeInfo(OpCodes.Move_wide, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4BitsWide),                                                          
            new OpCodeInfo(OpCodes.Move_wide_from16, RegisterFlags.Destination8BitsWide, RegisterFlags.Source16BitsWide),                                                          
            new OpCodeInfo(OpCodes.Move_wide_16, RegisterFlags.Destination16BitsWide, RegisterFlags.Source16BitsWide),                                                          
            new OpCodeInfo(OpCodes.Move_object, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Move_object_from16, RegisterFlags.Destination8Bits, RegisterFlags.Source16Bits), 
            new OpCodeInfo(OpCodes.Move_object_16, RegisterFlags.Destination16Bits, RegisterFlags.Source16Bits), 
            new OpCodeInfo(OpCodes.Move_result, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Move_result_wide, RegisterFlags.Destination8BitsWide), 
            new OpCodeInfo(OpCodes.Move_result_object, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Move_exception, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Return_void), 
            new OpCodeInfo(OpCodes.Return, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Return_wide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Return_object, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Const_4, RegisterFlags.Destination4Bits), 
            new OpCodeInfo(OpCodes.Const_16, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Const, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Const_high16, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Const_wide_16, RegisterFlags.Destination8BitsWide), 
            new OpCodeInfo(OpCodes.Const_wide_32, RegisterFlags.Destination8BitsWide), 
            new OpCodeInfo(OpCodes.Const_wide, RegisterFlags.Destination8BitsWide), 
            new OpCodeInfo(OpCodes.Const_wide_high16, RegisterFlags.Destination8BitsWide), 
            new OpCodeInfo(OpCodes.Const_string, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Const_string_jumbo, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Const_class, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Monitor_enter, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Monitor_exit, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Check_cast, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Instance_of, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Array_length, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.New_instance, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.New_array, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Filled_new_array, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Filled_new_array_range, RegisterFlags.Source16Bits), 
            new OpCodeInfo(OpCodes.Fill_array_data, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Throw, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Goto), 
            new OpCodeInfo(OpCodes.Goto_16), 
            new OpCodeInfo(OpCodes.Goto_32), 
            new OpCodeInfo(OpCodes.Packed_switch, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sparse_switch, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Cmpl_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Cmpg_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Cmpl_double, RegisterFlags.Destination8Bits, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Cmpg_double, RegisterFlags.Destination8Bits, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Cmp_long, RegisterFlags.Destination8Bits, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.If_eq, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.If_ne, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.If_lt, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.If_ge, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.If_gt, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.If_le, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.If_eqz, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.If_nez, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.If_ltz, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.If_gez, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.If_gtz, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.If_lez, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget_wide, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget_object, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget_boolean, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget_byte, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget_char, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aget_short, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput_wide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput_object, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput_boolean, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput_byte, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput_char, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Aput_short, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Iget, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iget_wide, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iget_object, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iget_boolean, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iget_byte, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iget_char, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iget_short, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput_wide, RegisterFlags.Source4BitsWide, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput_object, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput_boolean, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput_byte, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput_char, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Iput_short, RegisterFlags.Source4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Sget, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Sget_wide, RegisterFlags.Destination8BitsWide), 
            new OpCodeInfo(OpCodes.Sget_object, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Sget_boolean, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Sget_byte, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Sget_char, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Sget_short, RegisterFlags.Destination8Bits), 
            new OpCodeInfo(OpCodes.Sput, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sput_wide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Sput_object, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sput_boolean, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sput_byte, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sput_char, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sput_short, RegisterFlags.Source8Bits), 
            new OpCodeInvokeInfo(OpCodes.Invoke_virtual), 
            new OpCodeInvokeInfo(OpCodes.Invoke_super), 
            new OpCodeInvokeInfo(OpCodes.Invoke_direct), 
            new OpCodeInvokeInfo(OpCodes.Invoke_static), 
            new OpCodeInvokeInfo(OpCodes.Invoke_interface), 
            new OpCodeInvokeRangeInfo(OpCodes.Invoke_virtual_range), 
            new OpCodeInvokeRangeInfo(OpCodes.Invoke_super_range), 
            new OpCodeInvokeRangeInfo(OpCodes.Invoke_direct_range), 
            new OpCodeInvokeRangeInfo(OpCodes.Invoke_static_range), 
            new OpCodeInvokeRangeInfo(OpCodes.Invoke_interface_range), 
            new OpCodeInfo(OpCodes.Neg_int, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Not_int, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Neg_long, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Not_long, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Neg_float, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Neg_double, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Int_to_long, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Int_to_float, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Int_to_double, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Long_to_int, RegisterFlags.Destination4Bits, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Long_to_float, RegisterFlags.Destination4Bits, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Long_to_double, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Float_to_int, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Float_to_long, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Float_to_double, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Double_to_int, RegisterFlags.Destination4Bits, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Double_to_long, RegisterFlags.Destination4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Double_to_float, RegisterFlags.Destination4Bits, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Int_to_byte, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Int_to_char, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Int_to_short, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Add_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sub_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Mul_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Div_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Rem_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.And_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Or_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Xor_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Shl_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Shr_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Ushr_int, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Add_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Sub_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Mul_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Div_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Rem_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.And_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Or_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Xor_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Shl_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Shr_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Ushr_long, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Add_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Sub_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Mul_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Div_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Rem_float, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Add_double, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Sub_double, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Mul_double, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Div_double, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Rem_double, RegisterFlags.Destination8BitsWide, RegisterFlags.Source8BitsWide, RegisterFlags.Source8BitsWide), 
            new OpCodeInfo(OpCodes.Add_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Sub_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Mul_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Div_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Rem_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.And_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Or_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Xor_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Shl_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Shr_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Ushr_int_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Add_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Sub_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Mul_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Div_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Rem_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.And_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Or_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Xor_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Shl_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Shr_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Ushr_long_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Add_float_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Sub_float_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Mul_float_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Div_float_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Rem_float_2addr, RegisterFlags.DestAndSource4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Add_double_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Sub_double_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Mul_double_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Div_double_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Rem_double_2addr, RegisterFlags.DestAndSource4BitsWide, RegisterFlags.Source4BitsWide), 
            new OpCodeInfo(OpCodes.Add_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Rsub_int, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Mul_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Div_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Rem_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.And_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Or_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Xor_int_lit16, RegisterFlags.Destination4Bits, RegisterFlags.Source4Bits), 
            new OpCodeInfo(OpCodes.Add_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Rsub_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Mul_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Div_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Rem_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.And_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Or_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Xor_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Shl_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Shr_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
            new OpCodeInfo(OpCodes.Ushr_int_lit8, RegisterFlags.Destination8Bits, RegisterFlags.Source8Bits), 
        };
    }
}
