//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace FileBrowser
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
            
            public const int OpenFileLayout = 0x7f030001;
            
            public const int OpenFileRowLayout = 0x7f030002;
        }
        
        public sealed class Ids
        {
            
            public const int txtInfo = 0x7f040035;
            
            public const int cmdOpen = 0x7f040036;
            
            public const int lbPath = 0x7f040037;
            
            public const int list = 0x7f040038;
            
            public const int txtRow = 0x7f040039;
        }
    }
}
