//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Circle
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Attrs
        {
            
            public const int Color = 0x7f010000;
        }
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
        }
        
        public sealed class Styleables
        {
            
            public sealed class Circle
            {
                
                public const int Color = R.Attrs.Color & 0xffff;
                
public static readonly int[] AllIds = new[] { R.Attrs.Color };
            }
        }
    }
}
