//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RekenMaar
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
            
            public const int SettingActivityLayout = 0x7f030001;
            
            public const int TextView = 0x7f030002;
        }
        
        public sealed class Ids
        {
            
            public const int result = 0x7f04000d;
            
            public const int questionLayout = 0x7f04000e;
            
            public const int Ok = 0x7f04000f;
            
            public const int question = 0x7f040010;
            
            public const int @is = 0x7f040011;
            
            public const int answer = 0x7f040012;
            
            public const int keyLayout = 0x7f040013;
            
            public const int cmd1 = 0x7f040014;
            
            public const int cmd2 = 0x7f040015;
            
            public const int cmd3 = 0x7f040016;
            
            public const int cmd4 = 0x7f040017;
            
            public const int cmd5 = 0x7f040018;
            
            public const int cmd6 = 0x7f040019;
            
            public const int cmd7 = 0x7f04001a;
            
            public const int cmd8 = 0x7f04001b;
            
            public const int cmd9 = 0x7f04001c;
            
            public const int cmd0 = 0x7f04001d;
            
            public const int Erase = 0x7f04001e;
            
            public const int OptionMultiplication = 0x7f04001f;
            
            public const int tableChoosenTxt = 0x7f040020;
            
            public const int tableChoosen = 0x7f040021;
            
            public const int seekbar = 0x7f040022;
            
            public const int min = 0x7f040023;
            
            public const int max = 0x7f040024;
            
            public const int layoutSwitch = 0x7f040025;
            
            public const int isRandom = 0x7f040026;
            
            public const int OptionAddition = 0x7f040027;
            
            public const int layoutCountingTo = 0x7f040028;
            
            public const int CountingToTxt = 0x7f040029;
            
            public const int To10 = 0x7f04002a;
            
            public const int To50 = 0x7f04002b;
            
            public const int To100 = 0x7f04002c;
            
            public const int To500 = 0x7f04002d;
            
            public const int To1000 = 0x7f04002e;
            
            public const int layoutCountingWith = 0x7f04002f;
            
            public const int CountingWithTxt = 0x7f040030;
            
            public const int With0To10 = 0x7f040031;
            
            public const int With10To20 = 0x7f040032;
            
            public const int With20To50 = 0x7f040033;
            
            public const int With50To100 = 0x7f040034;
            
            public const int Cancel = 0x7f040035;
            
            public const int TextView01 = 0x7f040036;
            
            public const int actionbar_menu = 0x7f040037;
            
            public const int menu_options = 0x7f040038;
        }
        
        public sealed class Strings
        {
            
            public const int menu_options = 0x7f050000;
            
            public const int button_erase = 0x7f050001;
            
            public const int button_ok = 0x7f050002;
            
            public const int settings_div_mul_title = 0x7f050003;
            
            public const int settings_choosen_txt = 0x7f050004;
            
            public const int on_txt = 0x7f050005;
            
            public const int off_txt = 0x7f050006;
            
            public const int tables_until = 0x7f050007;
            
            public const int settings_add_sub_title = 0x7f050008;
            
            public const int count_until = 0x7f050009;
            
            public const int count_with = 0x7f05000a;
            
            public const int button_cancel = 0x7f05000b;
            
            public const int answer_correct = 0x7f05000c;
            
            public const int answer_incorrect = 0x7f05000d;
        }
        
        public sealed class Arrays
        {
            
            public const int gameType_array = 0x7f060000;
        }
        
        public sealed class Styles
        {
            
            public const int ViewStyle_FillWidth = 0x7f070000;
            
            public const int ViewStyle_WrapBoth = 0x7f070001;
            
            public const int ViewStyle_WrapBoth_Large = 0x7f070002;
            
            public const int ApplicationTheme = 0x7f070003;
            
            public const int CustomTextDefault = 0x7f070004;
            
            public const int CustomTextLarge = 0x7f070005;
            
            public const int ButtonStyle_WrapWidth = 0x7f070006;
            
            public const int TextViewStyle_Large = 0x7f070007;
            
            public const int CustomSpinnerTextStyle = 0x7f070008;
        }
        
        public sealed class Menus
        {
            
            public const int Menu = 0x7f080000;
        }
    }
}
