using Dot42.DexLib;

namespace Dot42.CompilerLib.RL
{
    /// <summary>
    /// RegisterSpec used for method variables
    /// </summary>
    internal sealed class VariableRegisterSpec : RegisterSpec
    {
        private readonly IVariable variable;

        /// <summary>
        /// Default ctor
        /// </summary>
        internal VariableRegisterSpec(Register register, Register wideRegister, TypeReference typeReference, IVariable variable) :
            base(register, wideRegister, typeReference)
        {
            this.variable = variable;
        }

        /// <summary>
        /// Gets the original variable
        /// </summary>
        public IVariable Variable
        {
            get { return variable; }
        }

        /// <summary>
        /// Is this variable generated by the compiler?
        /// </summary>
        public bool IsCompilerGenerated
        {
            get { return variable.IsCompilerGenerated; }
        }
    }
}
