//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace KiloBoltRobotGame
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int ic_launcher = 0x7f020000;
            
            public const int icon = 0x7f020001;
        }
        
        public sealed class Raws
        {
            
            public const int map1 = 0x7f030000;
        }
        
        public sealed class Ids
        {
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f050000;
        }
        
        public sealed class Styles
        {
            
            public const int AppBaseTheme = 0x7f060000;
            
            public const int AppTheme = 0x7f060001;
        }
    }
}
