//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace OpenGLES20Basic
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int ic_launcher = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int main = 0x7f030000;
        }
        
        public sealed class Ids
        {
        }
        
        public sealed class Strings
        {
            
            public const int hello = 0x7f050000;
            
            public const int app_name = 0x7f050001;
        }
    }
}
