//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace UsingGoogleMobAds
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainActivity = 0x7f020000;
        }
        
        public sealed class Ids
        {
            
            public const int mainLayout = 0x7f030035;
            
            public const int label = 0x7f030036;
            
            public const int editor = 0x7f030037;
            
            public const int button = 0x7f030038;
        }
    }
}
