//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Dot42Radio
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f030000;
            
            public const int PlayItemLayout = 0x7f030001;
        }
        
        public sealed class Id
        {
            
            public const int playList = 0x7f040036;
            
            public const int playItemText = 0x7f040037;
        }
    }
}
