//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace GooglePlusClient
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Attrs
        {
            
            public const int mapType = 0x7f010000;
            
            public const int cameraBearing = 0x7f010001;
            
            public const int cameraTargetLat = 0x7f010002;
            
            public const int cameraTargetLng = 0x7f010003;
            
            public const int cameraTilt = 0x7f010004;
            
            public const int cameraZoom = 0x7f010005;
            
            public const int uiCompass = 0x7f010006;
            
            public const int uiRotateGestures = 0x7f010007;
            
            public const int uiScrollGestures = 0x7f010008;
            
            public const int uiTiltGestures = 0x7f010009;
            
            public const int uiZoomControls = 0x7f01000a;
            
            public const int uiZoomGestures = 0x7f01000b;
            
            public const int useViewLifecycle = 0x7f01000c;
            
            public const int zOrderOnTop = 0x7f01000d;
        }
        
        public sealed class Drawables
        {
            
            public const int common_signin_btn_icon_dark = 0x7f020000;
            
            public const int common_signin_btn_icon_disabled_dark = 0x7f020001;
            
            public const int common_signin_btn_icon_disabled_focus_dark = 0x7f020002;
            
            public const int common_signin_btn_icon_disabled_focus_light = 0x7f020003;
            
            public const int common_signin_btn_icon_disabled_light = 0x7f020004;
            
            public const int common_signin_btn_icon_focus_dark = 0x7f020005;
            
            public const int common_signin_btn_icon_focus_light = 0x7f020006;
            
            public const int common_signin_btn_icon_light = 0x7f020007;
            
            public const int common_signin_btn_icon_normal_dark = 0x7f020008;
            
            public const int common_signin_btn_icon_normal_light = 0x7f020009;
            
            public const int common_signin_btn_icon_pressed_dark = 0x7f02000a;
            
            public const int common_signin_btn_icon_pressed_light = 0x7f02000b;
            
            public const int common_signin_btn_text_dark = 0x7f02000c;
            
            public const int common_signin_btn_text_disabled_dark = 0x7f02000d;
            
            public const int common_signin_btn_text_disabled_focus_dark = 0x7f02000e;
            
            public const int common_signin_btn_text_disabled_focus_light = 0x7f02000f;
            
            public const int common_signin_btn_text_disabled_light = 0x7f020010;
            
            public const int common_signin_btn_text_focus_dark = 0x7f020011;
            
            public const int common_signin_btn_text_focus_light = 0x7f020012;
            
            public const int common_signin_btn_text_light = 0x7f020013;
            
            public const int common_signin_btn_text_normal_dark = 0x7f020014;
            
            public const int common_signin_btn_text_normal_light = 0x7f020015;
            
            public const int common_signin_btn_text_pressed_dark = 0x7f020016;
            
            public const int common_signin_btn_text_pressed_light = 0x7f020017;
            
            public const int Icon = 0x7f020018;
        }
        
        public sealed class Layouts
        {
            
            public const int list_moments_activity = 0x7f030000;
            
            public const int main_list_item = 0x7f030001;
            
            public const int moment_row = 0x7f030002;
            
            public const int multi_moment_activity = 0x7f030003;
            
            public const int person_list_activity = 0x7f030004;
            
            public const int plus_one_activity = 0x7f030005;
            
            public const int share_activity = 0x7f030006;
            
            public const int sign_in_activity = 0x7f030007;
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f040000;
            
            public const int change_locale = 0x7f040001;
            
            public const int list_moments_title = 0x7f040002;
            
            public const int send_interactive_button_name = 0x7f040003;
            
            public const int sign_out_button_name = 0x7f040004;
            
            public const int revoke_access_button_name = 0x7f040005;
            
            public const int share_title = 0x7f040006;
            
            public const int share_prefill_text = 0x7f040007;
            
            public const int default_status = 0x7f040008;
            
            public const int greeting_status = 0x7f040009;
            
            public const int greeting_status_sign_in_required = 0x7f04000a;
            
            public const int greeting_status_error = 0x7f04000b;
            
            public const int loading_status = 0x7f04000c;
            
            public const int signing_in_status = 0x7f04000d;
            
            public const int signed_in_status = 0x7f04000e;
            
            public const int signed_out_status = 0x7f04000f;
            
            public const int plus_write_moment_status = 0x7f040010;
            
            public const int plus_remove_moment_status = 0x7f040011;
            
            public const int plus_one_small_name = 0x7f040012;
            
            public const int plus_one_medium_name = 0x7f040013;
            
            public const int plus_one_tall_name = 0x7f040014;
            
            public const int plus_one_standard_name = 0x7f040015;
            
            public const int plus_one_standard_ann_name = 0x7f040016;
            
            public const int plus_example_deep_link_id = 0x7f040017;
            
            public const int plus_example_deep_link_url = 0x7f040018;
            
            public const int plus_generic_error = 0x7f040019;
            
            public const int progress_message = 0x7f04001a;
            
            public const int common_google_play_services_install_title = 0x7f04001b;
            
            public const int common_google_play_services_install_text_phone = 0x7f04001c;
            
            public const int common_google_play_services_install_text_tablet = 0x7f04001d;
            
            public const int common_google_play_services_install_button = 0x7f04001e;
            
            public const int common_google_play_services_enable_title = 0x7f04001f;
            
            public const int common_google_play_services_enable_text = 0x7f040020;
            
            public const int common_google_play_services_enable_button = 0x7f040021;
            
            public const int common_google_play_services_update_title = 0x7f040022;
            
            public const int common_google_play_services_update_text = 0x7f040023;
            
            public const int common_google_play_services_unknown_issue = 0x7f040024;
            
            public const int common_google_play_services_unsupported_title = 0x7f040025;
            
            public const int common_google_play_services_unsupported_text = 0x7f040026;
            
            public const int common_google_play_services_update_button = 0x7f040027;
            
            public const int common_signin_button_text = 0x7f040028;
            
            public const int common_signin_button_text_long = 0x7f040029;
            
            public const int auth_client_using_bad_version_title = 0x7f04002a;
            
            public const int auth_client_needs_enabling_title = 0x7f04002b;
            
            public const int auth_client_needs_installation_title = 0x7f04002c;
            
            public const int auth_client_needs_update_title = 0x7f04002d;
            
            public const int auth_client_play_services_err_notification_msg = 0x7f04002e;
            
            public const int auth_client_requested_by_msg = 0x7f04002f;
        }
        
        public sealed class Colors
        {
            
            public const int common_signin_btn_dark_text_default = 0x7f050000;
            
            public const int common_signin_btn_dark_text_pressed = 0x7f050001;
            
            public const int common_signin_btn_dark_text_disabled = 0x7f050002;
            
            public const int common_signin_btn_dark_text_focused = 0x7f050003;
            
            public const int common_signin_btn_light_text_default = 0x7f050004;
            
            public const int common_signin_btn_light_text_pressed = 0x7f050005;
            
            public const int common_signin_btn_light_text_disabled = 0x7f050006;
            
            public const int common_signin_btn_light_text_focused = 0x7f050007;
            
            public const int common_signin_btn_default_background = 0x7f050008;
            
            public const int common_action_bar_splitter = 0x7f050009;
            
            public const int common_signin_btn_text_dark = 0x7f05000a;
            
            public const int common_signin_btn_text_light = 0x7f05000b;
        }
        
        public sealed class Ids
        {
            
            public const int none = 0x7f060035;
            
            public const int normal = 0x7f060036;
            
            public const int satellite = 0x7f060037;
            
            public const int terrain = 0x7f060038;
            
            public const int hybrid = 0x7f060039;
            
            public const int moment_list = 0x7f06003a;
            
            public const int moment_type = 0x7f06003b;
            
            public const int moment_title = 0x7f06003c;
            
            public const int person_list = 0x7f06003d;
            
            public const int plus_one_small_button = 0x7f06003e;
            
            public const int plus_one_medium_button = 0x7f06003f;
            
            public const int plus_one_tall_button = 0x7f060040;
            
            public const int plus_one_standard_button = 0x7f060041;
            
            public const int plus_one_standard_ann_button = 0x7f060042;
            
            public const int share_prefill_edit = 0x7f060043;
            
            public const int send_interactive_button = 0x7f060044;
            
            public const int sign_in_button = 0x7f060045;
            
            public const int sign_out_button = 0x7f060046;
            
            public const int revoke_access_button = 0x7f060047;
            
            public const int sign_in_status = 0x7f060048;
            
            public const int change_locale = 0x7f060049;
        }
        
        public sealed class Menus
        {
            
            public const int main_activity_menu = 0x7f070000;
        }
        
        public sealed class Styleables
        {
            
            public sealed class MapAttrs
            {
                
                public const int mapType = R.Attrs.mapType & 0xffff;
                
                public const int cameraBearing = R.Attrs.cameraBearing & 0xffff;
                
                public const int cameraTargetLat = R.Attrs.cameraTargetLat & 0xffff;
                
                public const int cameraTargetLng = R.Attrs.cameraTargetLng & 0xffff;
                
                public const int cameraTilt = R.Attrs.cameraTilt & 0xffff;
                
                public const int cameraZoom = R.Attrs.cameraZoom & 0xffff;
                
                public const int uiCompass = R.Attrs.uiCompass & 0xffff;
                
                public const int uiRotateGestures = R.Attrs.uiRotateGestures & 0xffff;
                
                public const int uiScrollGestures = R.Attrs.uiScrollGestures & 0xffff;
                
                public const int uiTiltGestures = R.Attrs.uiTiltGestures & 0xffff;
                
                public const int uiZoomControls = R.Attrs.uiZoomControls & 0xffff;
                
                public const int uiZoomGestures = R.Attrs.uiZoomGestures & 0xffff;
                
                public const int useViewLifecycle = R.Attrs.useViewLifecycle & 0xffff;
                
                public const int zOrderOnTop = R.Attrs.zOrderOnTop & 0xffff;
                
public static readonly int[] AllIds = new[] { R.Attrs.mapType, R.Attrs.cameraBearing, R.Attrs.cameraTargetLat, R.Attrs.cameraTargetLng, R.Attrs.cameraTilt, R.Attrs.cameraZoom, R.Attrs.uiCompass, R.Attrs.uiRotateGestures, R.Attrs.uiScrollGestures, R.Attrs.uiTiltGestures, R.Attrs.uiZoomControls, R.Attrs.uiZoomGestures, R.Attrs.useViewLifecycle, R.Attrs.zOrderOnTop };
            }
        }
    }
}
