//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Case6
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Ids
        {
        }
    }
}
