//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Id
        {
        }
        
        public sealed class Style
        {
            
            public const int MyTextView1 = 0x7f040000;
            
            public const int MyTheme = 0x7f040001;
        }
    }
}
