//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace AnimatedHelloWorld
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Anim
        {
            
            public const int Animation = 0x7f040000;
        }
        
        public sealed class Id
        {
            
            public const int theLabel = 0x7f050038;
        }
    }
}
