//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace AnimatedHelloWorld
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Anims
        {
            
            public const int Animation = 0x7f040000;
        }
        
        public sealed class Ids
        {
            
            public const int theLabel = 0x7f050035;
        }
    }
}
