//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SimpleGps
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int txStatus = 0x7f040035;
            
            public const int txProvider = 0x7f040036;
            
            public const int txAccuracy = 0x7f040037;
            
            public const int txLatitude = 0x7f040038;
            
            public const int txLongtitude = 0x7f040039;
            
            public const int txAltitude = 0x7f04003a;
            
            public const int txSpeed = 0x7f04003b;
            
            public const int txExtra = 0x7f04003c;
        }
    }
}
