//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace AccelerometerPlay
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int ball = 0x7f020000;
            
            public const int icon = 0x7f020001;
            
            public const int wood = 0x7f020002;
        }
        
        public sealed class Layouts
        {
            
            public const int main = 0x7f030000;
        }
        
        public sealed class Ids
        {
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f050000;
        }
    }
}
