//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpHeaderMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpHeaderMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestService.HttpHeaderMessages", typeof(HttpHeaderMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided todo already has an id specified. .
        /// </summary>
        internal static string IdSpecified {
            get {
                return ResourceManager.GetString("IdSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred processing this call. Please look in the log for more details..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GUID received..
        /// </summary>
        internal static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided id is not valid..
        /// </summary>
        internal static string InvalidIdSpecified {
            get {
                return ResourceManager.GetString("InvalidIdSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided todo is successfully deleted..
        /// </summary>
        internal static string TodoDeleted {
            get {
                return ResourceManager.GetString("TodoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested todo cannot be found..
        /// </summary>
        internal static string TodoNotFound {
            get {
                return ResourceManager.GetString("TodoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested todo is returned successfully..
        /// </summary>
        internal static string TodoReturned {
            get {
                return ResourceManager.GetString("TodoReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided todo is successfully updated and/or created..
        /// </summary>
        internal static string TodoUpdatedOrCreated {
            get {
                return ResourceManager.GetString("TodoUpdatedOrCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version is returned successfully..
        /// </summary>
        internal static string VersionReturned {
            get {
                return ResourceManager.GetString("VersionReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The xml message in the body of this message is not valid according to the XML schema definition..
        /// </summary>
        internal static string XsdValidationFailed {
            get {
                return ResourceManager.GetString("XsdValidationFailed", resourceCulture);
            }
        }
    }
}
