//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace TestAppDot42Async
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f020000;
        }
        
        public sealed class Ids
        {
            
            public const int mySynchronizedButton = 0x7f030035;
            
            public const int myNotSynchronizedButton = 0x7f030036;
            
            public const int txtStatus = 0x7f030037;
        }
    }
}
